// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Entities;
namespace Repositories;

public partial class MyShop330683525Context : DbContext
{
    public MyShop330683525Context(DbContextOptions<MyShop330683525Context> options)
        : base(options)
    {
    }

    public virtual DbSet<BasicSite> BasicSites { get; set; }

    public virtual DbSet<CartItem> CartItems { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<GeminiPrompt> GeminiPrompts { get; set; }

    public virtual DbSet<MainCategory> MainCategories { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrdersItem> OrdersItems { get; set; }

    public virtual DbSet<Platform> Platforms { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Rating> Ratings { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<SiteType> SiteTypes { get; set; }

    public virtual DbSet<Status> Statuses { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BasicSite>(entity =>
        {
            entity.HasKey(e => e.BasicSiteId).HasName("PK__BasicSit__FFB1C8E08C73AAF1");

            entity.Property(e => e.BasicSiteId).HasColumnName("BasicSiteID");
            entity.Property(e => e.SiteName).HasMaxLength(150);
            entity.Property(e => e.SiteTypeId).HasColumnName("SiteTypeID");

            entity.HasOne(d => d.BasicSitesPlatformsNavigation).WithMany(p => p.BasicSites)
                .HasForeignKey(d => d.BasicSitesPlatforms)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__BasicSite__Basic__60A75C0F");

            entity.HasOne(d => d.SiteType).WithMany(p => p.BasicSites)
                .HasForeignKey(d => d.SiteTypeId)
                .HasConstraintName("FK__BasicSite__SiteT__5EBF139D");

            entity.HasOne(d => d.UserDescriptionNavigation).WithMany(p => p.BasicSites)
                .HasForeignKey(d => d.UserDescription)
                .HasConstraintName("FK__BasicSite__UserD__5FB337D6");
        });

        modelBuilder.Entity<CartItem>(entity =>
        {
            entity.HasKey(e => e.CartId).HasName("PK__CartItem__51BCD7974A8D5B28");

            entity.Property(e => e.CartId).HasColumnName("CartID");
            entity.Property(e => e.ProductsId).HasColumnName("ProductsID");
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Valid).HasDefaultValue((byte)1);

            entity.HasOne(d => d.BasicSitesPlatformsNavigation).WithMany(p => p.CartItems)
                .HasForeignKey(d => d.BasicSitesPlatforms)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CartItems__Basic__73BA3083");

            entity.HasOne(d => d.Products).WithMany(p => p.CartItems)
                .HasForeignKey(d => d.ProductsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CartItems__Produ__70DDC3D8");

            entity.HasOne(d => d.UserDescriptionNavigation).WithMany(p => p.CartItems)
                .HasForeignKey(d => d.UserDescription)
                .HasConstraintName("FK__CartItems__UserD__72C60C4A");

            entity.HasOne(d => d.User).WithMany(p => p.CartItems)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CartItems__UserI__6FE99F9F");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__Categori__19093A2B2C41448C");

            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.CategoryDescreption)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.CategoryPrompt)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.ImgUrl)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.MainCategoryId).HasColumnName("MainCategoryID");

            entity.HasOne(d => d.MainCategory).WithMany(p => p.Categories)
                .HasForeignKey(d => d.MainCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Categorie__MainC__4D94879B");
        });

        modelBuilder.Entity<GeminiPrompt>(entity =>
        {
            entity.HasKey(e => e.PromptId).HasName("PK__GeminiPr__456CA7731D9C5917");

            entity.ToTable("GeminiPrompt");

            entity.Property(e => e.PromptId).HasColumnName("PromptID");
            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.Prompt).IsRequired();

            entity.HasOne(d => d.Category).WithMany(p => p.GeminiPrompts)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK__GeminiPro__Categ__5441852A");
        });

        modelBuilder.Entity<MainCategory>(entity =>
        {
            entity.HasKey(e => e.MainCategoryId).HasName("PK__MainCate__0290BDB6238CABD2");

            entity.HasIndex(e => e.MainCategoryName, "UQ__MainCate__121AD3E399483DB4").IsUnique();

            entity.Property(e => e.MainCategoryId).HasColumnName("MainCategoryID");
            entity.Property(e => e.MainCategoryName)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.MainCategoryPrompt)
                .IsRequired()
                .IsUnicode(false);
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__Orders__C3905BAF4C446210");

            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.BasicId).HasColumnName("BasicID");
            entity.Property(e => e.OrderDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.ReviewId).HasColumnName("ReviewID");
            entity.Property(e => e.StatusId).HasColumnName("StatusID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Basic).WithMany(p => p.Orders)
                .HasForeignKey(d => d.BasicId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Orders__BasicID__6B24EA82");

            entity.HasOne(d => d.Review).WithMany(p => p.Orders)
                .HasForeignKey(d => d.ReviewId)
                .HasConstraintName("FK__Orders__ReviewID__6D0D32F4");

            entity.HasOne(d => d.Status).WithMany(p => p.Orders)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__Orders__StatusID__6C190EBB");

            entity.HasOne(d => d.User).WithMany(p => p.Orders)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Orders__UserID__6A30C649");
        });

        modelBuilder.Entity<OrdersItem>(entity =>
        {
            entity.HasKey(e => e.OrderItemId).HasName("PK__OrdersIt__57ED06A184A30301");

            entity.Property(e => e.OrderItemId).HasColumnName("OrderItemID");
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.ProductsId).HasColumnName("ProductsID");

            entity.HasOne(d => d.BasicSitesPlatformsNavigation).WithMany(p => p.OrdersItems)
                .HasForeignKey(d => d.BasicSitesPlatforms)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrdersIte__Basic__797309D9");

            entity.HasOne(d => d.Order).WithMany(p => p.OrdersItems)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrdersIte__Order__778AC167");

            entity.HasOne(d => d.Products).WithMany(p => p.OrdersItems)
                .HasForeignKey(d => d.ProductsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrdersIte__Produ__76969D2E");

            entity.HasOne(d => d.UserDescriptionNavigation).WithMany(p => p.OrdersItems)
                .HasForeignKey(d => d.UserDescription)
                .HasConstraintName("FK__OrdersIte__UserD__787EE5A0");
        });

        modelBuilder.Entity<Platform>(entity =>
        {
            entity.HasKey(e => e.PlatformId).HasName("PK__Platform__F559F6DACDFB2FCA");

            entity.HasIndex(e => e.PlatformName, "UQ__Platform__85614BEE290C0594").IsUnique();

            entity.Property(e => e.PlatformId).HasColumnName("PlatformID");
            entity.Property(e => e.PlatformName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.PlatformsPrompt)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.ProductsId).HasName("PK__Products__BB48EDC5C71866C4");

            entity.Property(e => e.ProductsId).HasColumnName("ProductsID");
            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.ProductPrompt)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.ProductsName)
                .IsRequired()
                .IsUnicode(false);

            entity.HasOne(d => d.Category).WithMany(p => p.Products)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Products__Catego__5070F446");
        });

        modelBuilder.Entity<Rating>(entity =>
        {
            entity.HasKey(e => e.RatingId).HasName("PK__Ratings__FCCDF85CDD5F1398");

            entity.Property(e => e.RatingId).HasColumnName("RatingID");
            entity.Property(e => e.Host).HasMaxLength(50);
            entity.Property(e => e.Method)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.Path).HasMaxLength(50);
            entity.Property(e => e.RecordDate).HasColumnType("datetime");
            entity.Property(e => e.Referer).HasMaxLength(100);
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("PK__Review__74BC79AE80D846EC");

            entity.ToTable("Review");

            entity.Property(e => e.ReviewId).HasColumnName("ReviewID");
            entity.Property(e => e.ReviewImg).HasMaxLength(150);
        });

        modelBuilder.Entity<SiteType>(entity =>
        {
            entity.HasKey(e => e.SiteTypeId).HasName("PK__SiteType__85A71C863399C56D");

            entity.Property(e => e.SiteTypeId).HasColumnName("SiteTypeID");
            entity.Property(e => e.DescreptionPrompt)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.NamePrompt)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.SiteTypeDescreption)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.SiteTypeName)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Status>(entity =>
        {
            entity.HasKey(e => e.StatusId).HasName("PK__Statuses__C8EE2043427EB963");

            entity.Property(e => e.StatusId).HasColumnName("StatusID");
            entity.Property(e => e.StatusName)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CCAC3B95D3E9");

            entity.HasIndex(e => e.UserName, "UQ__Users__C9F284568D12EF60").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.GoogleId).HasColumnName("GoogleID");
            entity.Property(e => e.BasicId).HasColumnName("BasicID");
            entity.Property(e => e.FirstName).HasMaxLength(100);
            entity.Property(e => e.LastName).HasMaxLength(100);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Phone).HasMaxLength(10);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Basic).WithMany(p => p.Users)
                .HasForeignKey(d => d.BasicId)
                .HasConstraintName("FK__Users__BasicID__6477ECF3");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}