// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class BasicSite
{
    public long BasicSiteId { get; set; }

    public string SiteName { get; set; }

    public long? SiteTypeId { get; set; }

    public long? UserDescription { get; set; }

    public long BasicSitesPlatforms { get; set; }

    public virtual Platform BasicSitesPlatformsNavigation { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual SiteType SiteType { get; set; }

    public virtual GeminiPrompt UserDescriptionNavigation { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}