// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class CartItem
{
    public long CartId { get; set; }

    public long UserId { get; set; }

    public long ProductsId { get; set; }

    public byte? Valid { get; set; }

    public long? UserDescription { get; set; }

    public long BasicSitesPlatforms { get; set; }

    public virtual Platform BasicSitesPlatformsNavigation { get; set; }

    public virtual Product Products { get; set; }

    public virtual User User { get; set; }

    public virtual GeminiPrompt UserDescriptionNavigation { get; set; }
}