// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class Category
{
    public long CategoryId { get; set; }

    public long MainCategoryId { get; set; }

    public string CategoryName { get; set; }

    public string CategoryPrompt { get; set; }

    public string ImgUrl { get; set; }

    public string CategoryDescreption { get; set; }

    public virtual MainCategory MainCategory { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}