// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class GeminiPrompt
{
    public long PromptId { get; set; }

    public string Prompt { get; set; }

    public long? CategoryId { get; set; }

    public virtual ICollection<BasicSite> BasicSites { get; set; } = new List<BasicSite>();

    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    public virtual Category Category { get; set; }

    public virtual ICollection<OrdersItem> OrdersItems { get; set; } = new List<OrdersItem>();
}