// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class OrdersItem
{
    public long OrderItemId { get; set; }

    public long ProductsId { get; set; }

    public long OrderId { get; set; }

    public long? UserDescription { get; set; }

    public long BasicSitesPlatforms { get; set; }

    public virtual Platform BasicSitesPlatformsNavigation { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Products { get; set; }

    public virtual GeminiPrompt UserDescriptionNavigation { get; set; }
}