// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class Platform
{
    public long PlatformId { get; set; }

    public string PlatformName { get; set; }

    public string PlatformsPrompt { get; set; }

    public virtual ICollection<BasicSite> BasicSites { get; set; } = new List<BasicSite>();

    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    public virtual ICollection<OrdersItem> OrdersItems { get; set; } = new List<OrdersItem>();
}