// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class Product
{
    public long ProductsId { get; set; }

    public long CategoryId { get; set; }

    public string ProductsName { get; set; }

    public double Price { get; set; }

    public string ProductPrompt { get; set; }

    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    public virtual Category Category { get; set; }

    public virtual ICollection<GeminiPrompt> GeminiPrompts { get; set; } = new List<GeminiPrompt>();

    public virtual ICollection<OrdersItem> OrdersItems { get; set; } = new List<OrdersItem>();
}