// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class Review
{
    public long ReviewId { get; set; }

    public string ReviewText { get; set; }

    public double Stars { get; set; }

    public string ReviewImg { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}