// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class SiteType
{
    public long SiteTypeId { get; set; }

    public string SiteTypeName { get; set; }

    public string SiteTypeDescreption { get; set; }

    public string NamePrompt { get; set; }

    public string DescreptionPrompt { get; set; }

    public double Price { get; set; }

    public virtual ICollection<BasicSite> BasicSites { get; set; } = new List<BasicSite>();
}