<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="C:\Users\1\Dropbox\My PC (DESKTOP-R5RADSP)\Desktop\dot_net\git-dot.net-project\WebApiShope\WebApiShope\.editorconfig" />
    <None Include="wwwroot\NewFolder\enter.html" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\1\Dropbox\My PC %28DESKTOP-R5RADSP%29\Desktop\dot_net\git-dot.net-project\WebApiShope\WebApiShope\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.*" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
    <PackageReference Include="NLog.MailKit" Version="6.0.5" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="6.1.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.12.14" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DTO\DTO.csproj" />
    <ProjectReference Include="..\Services\Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\" />
  </ItemGroup>

</Project>
